### ISSUE TITLE
3 Weeks - [메서드 참조를 디버깅 할 때의 스택 트레이스]

### ISSUE THREAD

**Issue by MadCom96** [SSAFY-Book-Study/modern-java-in-action#40]
## 문제
디버그 진행 시, 스택 트레이스를 해석하는 문제

## contents - 세부 내용
본문의 chapter9에서 메서드 참조를 할 때 오류가 나면, 스택 트레이스에 알아보기 힘든 다른 이름이 뜬다는 것을 알았습니다.

람다 예 ) at Debugging.lambda$main$0(Debugging.java:6)
메서드 참조 예 ) at Debugging$$Lambda$5/284720968.apply(Unknown Source)

아무런 연고도 없는 숫자이름 등을 만들어 내지는 않았을 것 같은데, 위와 같은 예제에서 보여준 이름들에 의미가 있다면 무엇일까요?
이를 통해 디버깅을 할 때 정보를 얻는 용도로 사용할 수 있는지 궁금합니다!

## 참고
317페이지, 9장

**Comment by wlwlwon** [comment]
### 문제점

람다표현식과 메서드 참조 사용시 스택 트레이스에서 아무런 연고도 없는 숫자이름 등을 만들어 내지는 않았을 것 같은데, 위와 같은 예제에서 보여준 이름들에 의미가 있다면 무엇일까?

람다 표현식

- 함수를 하나의 식으로 표현 익명 함수로서 이름이 없음
- 메서드로 전달할 수 있는 익명 함수를 단순화한 것

### 람다표현식 사용시 스택 트레이스

```java
import java.util.*;
public class Debugging{
 public static void main(String[] args) {
 List<Point> points = Arrays.asList(new Point(12, 2), null);
 points.stream().map(p -> p.getX()).forEach(System.out::println);
 }
}
////////////////////////////////////////
at Debugging.lambda$main$0(Debugging.java:6) 여기 $0은 무슨 의미일까?
 at Debugging$$Lambda$5/284720968.apply(Unknown Source)
```

스택 트레이스에서 

- "lambda": 이 부분은 이 메서드가 람다 표현식에 관련된 것임을 나타냄
- "main": 이 메서드가 **`main`** 메서드 내에서 정의되었음을 나타냄
- "0": 이 메서드가 해당 람다 표현식 내에서 첫 번째로 정의된 메서드임을 나타냄

### 람다 표현식을 메서드 참조 사용시 스택 트레이스

```java
points.stream().map(Point::getX).forEach(System.out::println);

Exception in thread "main" java.lang.NullPointerException
 at Debugging$$Lambda$5/284720968.apply(Unknown Source) 이것은 무슨 의미일까?
 at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline
 .java:193)
```

메서드 참조를 사용해도 스택 트레이스에는 메서드명이 나타나지 않고 임의의 숫자값이 나타남. 

숫자와 같은 경우 java 컴파일러와 런타임 시간에 자동으로 생성되며 주로 내부적으로 사용됨 이러한 이름은 직접적으로 의미를 갖지는 않음

Java의 스트림 API에서 **`forEach`**최종 연산이 동작할때 이러한 연산들은 스트림 파이프라인 내에서 일어나며 스트림 요소를 처리하기 위한 내부 로직을 실행함. 스트림에서 병렬처리하기에 직접적으로 스택 트레이스에는 표시되지 않는다.

정리

- 람다표현식은 익명함수여서 스택트레이스에서 직관적인 정보를 얻기 힘듬
- 람다 표현식과 관련한 스택 트레이스는 이해하기 어려울 수 있다는 점을 염두
